### PR TITLE
fixed #49

### LINKED ISSUE #49: Add localization in map
On [Oblyk map](https://oblyk.org/carte-des-falaises) add localization button

### PR DESCRIPTION
**Pull request by mjamroz**
basic button with localisation.

### CODE REVIEW

**Comment by lucien-chastan** [comment]
Why this pull request? Is there the same code in this [one](https://github.com/lucien-chastan/oblyk/pull/66/files)?

**Comment by mjamroz** [comment]
yes, is the same but is a bit more. 
https://github.com/lucien-chastan/oblyk/pull/65/commits/f23216fd19f95d1a89e12303372514ea451c8d2c is localisation button on map (solves issue #49 ), and https://github.com/lucien-chastan/oblyk/pull/66/files solves issues #49 and #63 (tab of route types of "crosses" page).

i was drunk when i made both, sorry, and forgot to create new branch for pull request related with #49 . Actually im again drunk and not sure if i should answer questions now. eh

**Comment by lucien-chastan** [comment]
Be careful drinking too slow your healing ! but then you will work more for oblyk, so keep drinking ^^

**Comment by lucien-chastan** [comment]
I think I'm going to merge the branch with two evolutions, and remove this one

**Comment by mjamroz** [comment]
for the commit i made modifications for themap - i forgot to add leaflet localisation plugin in this commit. two files specified here:
```
href="/framework/leaflet/L.Control.Locate.min.css">
...
src="/framework/leaflet/L.Control.Locate.min.js">
```
in resources/views/pages/map/map.blade.php

Then, keep in mind it wont work till you add them ;) Sorry again.

**Pull request merged**
