### PR TITLE
Search topo by name

### PR DESCRIPTION
**Pull request by mjamroz**
When I try to add topo to the sector/crag i have to click many times "expand radius" cause my topo (escalade plasir) has no specified region. Searching by name could/would/might be useful.

### CODE REVIEW

**Comment by lucien-chastan** [comment]
It's cool ! but I proposing some changes :

- add timeout on key press before Ajax get (approximately 500 ms / 1000 ms) and if you retype a letter before the end of timeout you reset this ... You know what I mean ?.
- reorganize the search on 2 tabs, _"search by proximity"_ and _"search by name"_
- push the search input on the top of result list

Example :
serach by name

What do you think ?

(I can make the changes if you want?)

**Comment by mjamroz** [comment]
oki, thanks! 
perhaps tomorrow will make changes you suggested

**Comment by lucien-chastan** [comment]
Yes !  

You can use [materialize tab](http://materializecss.com/tabs.html)  
it's possible that you are problems with initialization, because it's an ajax popup, but maybe not, I can't remember if I fixed that

**Comment by mjamroz** [comment]
@lucien-chastan done. again pushed junk from public/*, but in general i modified three files:
+ resources/assets/js/app.js (to init tabs)
+ resources/assets/js/crag.js
+ resources/views/modal/topoCrag.blade.php

\+translations (btw i dont speak french, "search by proximity" was taken from google translator, hope it is correct).

**Comment by lucien-chastan** [comment]
Following the public folder is not a good idea, I have to change that.
I don't speak English ^^ I use [DeepL](https://www.deepl.com/translator) to translate, I think it's better than google trad

**Comment by lucien-chastan** [comment]
Hi!

I have a problem with git, maybe you can help me?

To see your modifications I added you in my remotes
```
$ git remote -v
mjamroz https://github.com/mjamroz/oblyk (fetch)
mjamroz https://github.com/mjamroz/oblyk (push)
origin https://github.com/lucien-chastan/oblyk.git (fetch)
origin https://github.com/lucien-chastan/oblyk.git (push)
```

so I can stand on your branch

I made some modifications on your branch and I push: 
`$ git push origin mjamroz/search_topo_by_name`

did you get anything? I can't find my modifications on github...

**Comment by mjamroz** [comment]
hi again. i got nothing. But just now i added you to collaborators of this fork (i added you as a collaborator to your own code XD ), maybe it help?

**Comment by lucien-chastan** [comment]
hum ...  
I need to document myself

here's what I changed (sorry it's really not sexy as a presentation)

[diff.txt](https://github.com/lucien-chastan/oblyk/files/1867967/diff.txt)

**Comment by lucien-chastan** [comment]
I accepted yours invitation, you see my last commit on yours branch ?
(I think that not, I don't see it)

**Comment by mjamroz** [comment]
Would be nice to elaborate some better way of cooperation ;-). I tried to `git apply diff.txt` but didnt work, then i applied diff manually, but for topoCrag template it was too much to change then i give up.
Seems pushing to my branch didnt work (i can't see your commit in this fork).

But what if you push modified-by-you version to your beta, and i will fetch it again to my fork/beta having up-to-date? I know is not the best way, but maybe easier than diff's. Dont know.

**Comment by lucien-chastan** [comment]
Yeah, I think I did it.
I made a copy of your branch on my repository, and I pushed it on your origin... something like that ^^

Sorry for the problems I discovered collaboration from a fork

**Comment by mjamroz** [comment]
if you are brave enough believing my code doesn't burn oblyk :).

If you have any other plans/todos to code something and are already bored of coding, let me know - maybe i could do a bit.

**Comment by lucien-chastan** [comment]
Hi @mjamroz  !

I have push your branch into [Oblyk Beta](https://beta.oblyk.org)  
You can test that if you want.

It's okay with me, I'm thinking of merging it with master on Tuesday or Thursday.

**Comment by lucien-chastan** [comment]
for your question about stuff you could code

I think that i'm going to create one issue for eache bugs or enhancements (you can create some to)

If you would like work on issue, you asign it to yourself. In this way, we can discuss to best method or strategy befor starting the developpement.

What do you think of this workflow?

**Comment by mjamroz** [comment]
@lucien-chastan  good idea about issues!
and about beta version - it seems that tabs are not initialized (both are displayed at the same tab).

 Are you using materialize beta, or normal release? I noticed in normal (which i tested) we should add tabs init. to ready: function() {} (what i've added to app.js), but for beta - to onOpenEnd: function(){} (i believe). But im not sure if that is the case. Any ideas?

**Comment by mjamroz** [comment]
Thanks for the investigation and merging!! :drooling_face:

**Pull request merged**
