### PR TITLE
Fix for #48

### PR DESCRIPTION
**Pull request by mjamroz**
In this pull request you have script to update wrong min_gap_val and added rune in majInformation to avoid it in the future.

### CODE REVIEW

**Comment by lucien-chastan** [comment]
You're fast!

Thanks for the console script! I don't think enough that we can do that (I learned laravel with oblyk, I still have things to learn!. and I do symfony with taff, I find it less well)

I'll test that on a beta base.

**Comment by lucien-chastan** [comment]
We have a problem when sector or crag have only routes with "?" grade ...
For example : [blocs du cimaï](https://oblyk.org/fr/site-escalade/2194/les-blocs-du-cimai) sector Kochise, you have 3 routes with ? grade
When you run php artisan oblyk:fix_lower_grade in terminal, I have this exception : `Trying to get property 'routeSections' of non-object`
maybe add test on the number of route  that have more than one grade above 0 ?

**Comment by mjamroz** [comment]
Fock. Thanks for testing, Lucien. I totally take no into consideration cases when crag/sector has no other routes than only "?". Will be back to you soon (today) with fix.

**Comment by mjamroz** [comment]
Maybe now you would like to merge with commit df60c7f845d83a711c5a0f9761e5ac5e906899e3 and re run oblyk:fix_...

**Comment by lucien-chastan** [comment]
Perfect ! I merge that on master today !

Thanks a lot !

**Pull request closed without merging**
