### PR TITLE
grouping by voie type on the crags map

### PR DESCRIPTION
**Pull request by mjamroz**
By some reason leaflet doesnt display checkboxes for overlayed maps. But ut should. Even in the html those elements are as a input type=checkbox. Maybe you know where to look for the solution.

Except that one ugly problem, now it is possible to dis/enable subgroups on the map. 

also i recreated my fork. let see what will happen ;)
sss

### CODE REVIEW

**Comment by lucien-chastan** [comment]
Ooh, it's much cleaner!!
Did you check if it's matrialize that's overwriting the checkbox style with the code inspector?
I'll watch it tonight.
It's cool, it has little code for good evolution ^^

**Comment by mjamroz** [comment]
yes, you were right. And i just found a solution https://stackoverflow.com/questions/40155017/materialize-css-not-showing-multiple-checkboxes-with-leaflet-web-mapping-overlay

Now, small bugfixed and will push (hopefully today).

**Comment by mjamroz** [comment]
in the current commit with checkboxes. but  anyway, still with echoe of shitty bug i described in the commit comment.

ccc

**Comment by lucien-chastan** [comment]
I see the problem, if it's a site with several types of climbing then it doesn't work... maybe you have to do a function by hand that is triggered by clicking on the checkboxes

**Comment by lchastan** [comment]
What do you think about going further?

let's say we have a filter button on the map, you click on it and a side pane opens (a bit like the information of a route)

In this pane you would have, a checkbox per type of climbing and a double range for the max min rating to look for (we could add later other filters, orientations?, season?, etc.)

and a button to submit.

technically : we delete the markers from the map, and we have a controller that sends us a new list (the all in ajax :)

**Comment by mjamroz** [comment]
@lchastan 
Related to filter by route grade, im doing:
```
+   6             RouteSection::select(['grade', 'sub_grade', 'grade_val'])                                                                                                      
+   5                 ->distinct()                                                                                                                                               
+   4                 ->orderBy('grade_val', 'asc')                                                                                                                              
+   3                 ->get()                                                                                                                                                    
+   2                 ->each(function($e) {                                                                                                                                      
+   1                     $e->grade .= $e->sub_grade;                                                                                                                            
+ 29                      unset($e->sub_grade);                                                                                                                                  
+   1                 })      
```
on the data from initial seed of database, getting:
```

0 |  
-- | --
grade | "5a"
grade_val | 25
1 |  
grade | "5c"
grade_val | 30
2 |  
grade | "6a"
grade_val | 31
3 |  
grade | "6b"
grade_val | 33
4 |  
grade | "6b+"
grade_val | 34
5 |  
grade | "6c"
grade_val | 35
6 |  
grade | "7a+"
grade_val | 37
7 |  
grade | "7a+"
grade_val | 38
8 |  
grade | "7c"
grade_val | 41

```

Why grade_val 37 and 38 have the same grade (7a+). It shouldn't be assigned 1:1 ?

**Comment by lucien-chastan** [comment]
I think I'm removing the +/-/?  To determine the value of the grade.  Where do you find this table?

In [route controller](https://github.com/lucien-chastan/oblyk/blob/master/app/Route.php) ?

**Comment by mjamroz** [comment]
i found you're transforming user input of grade to some number in Route.php and you store both in the DB (RouteSection model) then I thought - instead of typing mapping grade->number or using `Route::gradeToVal()` i would simply use the stored values instead of transforming every time. But since you're shipping +/- then perfect, even better/cleaner. :+1:

**Comment by mjamroz** [comment]
ah, no. but if you would skip +/- then 7a+ would have the same number. But in this case it  7a+ has two different. then i still dont understand this transformation :cry:

**Comment by mjamroz** [comment]
Currently it looks like below and it seems it works (https://github.com/mjamroz/oblyk/commit/3298e0b442cc8bcdc5f91fe461ccf29c1435a85b ). Few things:

- my design smells badly
- range slider has no tooltip enabled by default. I've no idea how to enable it (i know how to do it in nouislider, but not the one modified by materialize ppl)
- there are some ugly labels of climb type (got from climbs table). In production they are the same? Maybe i should create some seeder?

screenshot_2018-05-22_21-49-32

**Comment by lucien-chastan** [comment]
It's starting to look good!

For design, I propose : 
- Reduce title font-size (a little bit taller than normal), I think that bold is sufficient
- Puts the checkbox on tow columns
- give a bottom border to the titles (1px and light gray, like a "Community activity since yesterday" sub titles on [home page](https://oblyk.org/en))
- for double range grade, maybe put tow permanent label on right and left of double range (like the image at the bottom of the comment)
- align the buttons on the right and switch "submit" and "cancel"
- give a black color for text on the cancel button

range

I will soon push your branch on beta version, you can test with a lot of data

at least it's great! it's a real improvement. Then we can add other nice filters (approach time, orientation, favorable season) but already let's start by type and rating :)

**Comment by lucien-chastan** [comment]
I wanted to get your modifications to put on the Beta version but in fact you haven't commited yet.

**Comment by lucien-chastan** [comment]
Ok, I close this pull request

**Pull request closed without merging**
